const fetch = require('node-fetch');

exports.handler = async (event, context) => {
    const { pdfText } = JSON.parse(event.body);

    // Retrieve the GPT-4 Mini API key from Netlify environment variables
    const apiKey = process.env.GPT4_MINI_API_KEY;

    try {
        // Call the GPT-4 Mini API
        const response = await fetch('https://api.gpt4mini.com/v1/generate', {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
                'Authorization': `Bearer ${apiKey}`
            },
            body: JSON.stringify({
                prompt: `Generate multiple choice questions from this text: ${pdfText}`,
                max_tokens: 500 // Adjust the token limit as needed
            })
        });

        if (!response.ok) {
            throw new Error('Error with GPT-4 Mini API request');
        }

        const data = await response.json();

        // Return the questions generated by the GPT-4 Mini API
        return {
            statusCode: 200,
            body: JSON.stringify({ questions: data.choices[0].text.trim() })
        };
    } catch (error) {
        // Handle errors and return a meaningful message
        return {
            statusCode: 500,
            body: JSON.stringify({ error: error.message })
        };
    }
};
